### ISSUE TITLE
demo跑不通

### ISSUE THREAD

**Issue by aoping** [132yse/voe#4]
![image](https://user-images.githubusercontent.com/12975084/69136863-9c602280-0af6-11ea-9183-a0148c34dc04.png)

demo示例跑不通，点击按钮，直接报错，原因是我们的textnode的nodeValue是number类型
即以下代码判断出错
```
isNum(op[1])
      ? getElement(op[0]).removeChild(op[1])
      : (getElement(op[0]).nodeValue = op[1])
```
跑了```getElement(op[0]).removeChild(op[1])```

**Comment by 132yse** [comment]
不好意思，这块我临时改的，回家我修复下

**Comment by 132yse** [comment]
修复了√现在demo可以跑通了
