### ISSUE TITLE
code issue

### ISSUE THREAD

**Issue by fantasticsoul** [132yse/voe#5]
voe/src/h.ts line 25
```
if (vnode == null || vnode === true || vnode === false) {
```
第一部分那里是不是少了个 = ？

**Comment by fantasticsoul** [comment]
voe/src/reactivity.ts line 32
```
return Reflect.defineProperty(target, key,receiver)
```
逗号后面少了个空格，貌似你没有自格式化的插件哦？

**Comment by 132yse** [comment]
> 第一部分那里是不是少了个 = ？
没少，这样可以涵盖 undefined
> 逗号后面少了个空格，貌似你没有自格式化的插件哦？
忘记按了
